import { ReactNode, Suspense } from 'react';

import type { Metadata } from 'next';

import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';

import { ReactQueryProvider, StyledComponentsRegistry } from '@/libs/providers';
import { Yekan } from '@/theme/font.config';
import '@/theme/globals.css';
import '@/theme/theme.config.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html className={Yekan.variable} lang='fa' dir='rtl'>
      <body>
        <ReactQueryProvider>
          <StyledComponentsRegistry>
            <Theme accentColor='gray' grayColor='gray' radius='large' scaling='100%'>
              <Suspense>{children}</Suspense>
            </Theme>
          </StyledComponentsRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
