import RecentPlanImage from '../../../public/image/avatar.png';
import BannerImage from '../../../public/image/landing-banner.png';

export const recentPlansData = [
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
];

export const recentPointsData = [
  {
    pictureUrl: BannerImage,
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
  {
    pictureUrl: BannerImage,
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
  {
    pictureUrl: BannerImage,
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
  {
    pictureUrl: BannerImage,
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
];

export const recentTourData = [
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
  {
    image: RecentPlanImage,
    userName: 'نام کاربر',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
    badge: ['طبیعت گردی', 'تاریخ گردی'],
  },
];
