export const recentPlansData = [
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
  {
    userName: 'نام کاربر',
    creationDate: 'تاریخ ساخت',
    from: 'تهران',
    to: 'شیراز',
    travelDays: 10,
    companionCount: 8,
    isPremium: true,
  },
];

export const recentPointsData = [
  {
    pictureUrl: 'https://www.conventionalcommits.org/img/git-flow--welcome.png',
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
  {
    pictureUrl: 'https://www.conventionalcommits.org/img/git-flow--welcome.png',
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
  {
    pictureUrl: 'https://www.conventionalcommits.org/img/git-flow--welcome.png',
    title: 'نام و عنوان',
    rating: 4.5,
    address: 'تهران، خیابان اول، محله دوم، کوچه سوم، پلاک چهارم',
  },
];
